# Generated by Django 4.2 on 2023-04-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-pub_date']},
        ),
    ]
